# Generated by Django 4.0.6 on 2022-07-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', "ayant la possibilité de changer le titre d'un billet de blog")]},
        ),
    ]
