# Generated by Django 4.0.6 on 2022-07-08 22:32

from django.db import migrations

def author_to_contributors(apps, schema):
    Blog=apps.get_model('blog','Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributor.add(
                blog.author,through_defaults={'contribution':'Auteur principal'}
            )



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcontributor_blog_contributors_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.RunPython(author_to_contributors)
    ]
